### ISSUE TITLE
Is anyone else getting an error about their API key?

### ISSUE THREAD

**Issue by annetters** [forrestthewoods/fts_commute_visualizer#1]
Awesome tool and thank you for sharing! The visualizations are beautiful.

Is anyone else getting an error about their API key, when they're _really_ sure it's correct? I'm on latest Chrome doing nothing special.

`Google Maps API warning: InvalidKey https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key
tB.j @ maps.googleapis.com/maps-api-v3/api/js/28/11/util.js:219`

**Comment by cyraju** [comment]
Harv you changed API key on both the places?

**Comment by annetters** [comment]
@cyrus22038 A-ha, that was it! For others who run into this issue:

See <script async defer> at line 1558. This is the one place that the variable API_KEY is not reused.
